#!/bin/bash

DIR1=$HOME/pkgs/void-packages/
DIR2=$HOME/pkgs/void-packages/srcpkgs

cd "$DIR1" || exit
git pull

cd "$DIR2" || exit
if [[ -d "$1" ]]
then
	cd "$DIR1" || exit
	./xbps-src pkg "$1" && sudo xbps-install --repository hostdir/binpkg "$1"
else
	printf "No se encuentra $1\n"
fi
